version: '3'
services:
    poll:
        build: ./poll/
        restart: on-failure
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - "5000:80"
        networks:
            - poll-tier
    redis:
        image: redis:alpine
        restart: on-failure
        ports:
            - "6379"
        networks:
            - poll-tier
            - back-tier
    worker:
        build: ./worker/
        environment:
            - REDIS_HOST=redis
            - DB_HOST=db
        restart: on-failure
        networks:
            - back-tier
    db:
        image: postgres:latest
        restart: on-failure
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - db-data:/var/lib/postgresql/data
        networks:
            - result-tier
            - back-tier
    result:
        build: ./result/
        restart: on-failure
        environment:
            - CONNECTION_PORT=80
            - DB_SERVICE=db
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=postgres
        ports:
            - "5001:80"
        networks:
            - result-tier

volumes:
    db-data:

networks:
    poll-tier:
        driver: bridge
    result-tier:
        driver: bridge
    back-tier:
        driver: bridge